version: 2
jobs:
   build:
     docker:
       - image: ubuntu:16.04
     environment:
       LC_ALL: C.UTF-8
       LANG: C.UTF-8
     steps:
       - run:
           name: install git
           command: |
               apt-get update
               apt-get install -y git
       - checkout
       - run:
            name: install dependencies
            command: |
                apt-get install -y software-properties-common
                apt-get update
                apt-get install -y python3-venv
                apt-get install -y python3-dev
                 python3 -m venv venv
                . venv/bin/activate
                pip install --upgrade pip
                
       - run:
           name: run tests
           command: |
               . venv/bin/activate
               pytest