version: 2
jobs:
   build:
     machine: true
     environment:
       LC_ALL: C.UTF-8
       LANG: C.UTF-8
     steps:
       - run:
           name: install git
           command: |
               sudo apt-get update
               sudo apt-get install -y git
       - checkout
       - run:
            name: install dependencies
            command: |
                sudo apt-get install -y software-properties-common \
                    apt-transport-https \
                    ca-certificates \
                    curl \
                    gcc \
                    libssl-dev \
                    gnupg2
                sudo bash -c "yes | add-apt-repository ppa:jonathonf/python-3.6 && apt-get update && apt-get install -y python3.6"
                sudo apt-get update
                sudo apt-get install -y python3.6-venv
                sudo apt-get install -y python3.6-dev
                python3.6 -m venv venv
                . venv/bin/activate
                pip install --upgrade pip
                pip install -r requirements.txt
       - run:
           name: run tests
           command: |
               . venv/bin/activate
               docker pull golemfactory/base:1.2
               docker pull golemfactory/blender:1.4
               docker pull golemfactory/luxrender:1.2
               docker pull golemfactory/image_metrics:1.2
               pytest
