version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.6
     steps:
       - checkout
       - run:
           command: |
             python3 -m venv venv
             . venv/bin/activate
             pip3 install -r requirements.txt

       - run:
           command: |
             . venv/bin/activate
             python3 setup.py develop
             pytest
